name: dante
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1
  - python=3.12.0
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - antlr4-python3-runtime==4.9.3
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - contourpy==1.3.2
      - cycler==0.12.1
      - einops==0.8.1
      - filelock==3.13.1
      - fonttools==4.58.0
      - fsspec==2024.6.1
      - huggingface-hub==0.31.4
      - idna==3.10
      - iopath==0.1.10
      - jinja2==3.1.4
      - kiwisolver==1.4.8
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==2.1.2
      - omegaconf==2.3.0
      - packaging==25.0
      - pandas==2.2.3
      - pillow==11.0.0
      - portalocker==3.1.1
      - protobuf==6.31.0
      - pygments==2.19.1
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==14.0.0
      - safetensors==0.5.3
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - six==1.17.0
      - sympy==1.13.3
      - timm==0.6.13
      - tokenizers==0.21.1
      - torch==2.7.0
      - torchaudio==2.7.0
      - torchvision==0.22.0
      - tqdm==4.67.1
      - transformers==4.47.1
      - triton==3.3.0
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - urllib3==2.4.0
